---
accessToken:
  source:
    command:
      shell: ""
      command: ""
      noReuseToken: false
    clientCredentials:
      issuer: ""
      clientID: ""
      clientSecret: ""
    generate:
      issuer: ""
      subject: ""
      expiry: ""
  exchange:
    issuer: ""
    grantType: ""
    tokenType: ""
